install.packages("dplyr")
library(dplyr)
help(package = "dplyr")
setwd("~/GitHub/r-data-frames-acnicklow")
shrubs <- read.csv("shrub-volume-experiment.csv")
names(shrubs)
str(shrubs)
head(shrubs)
print(select(shrubs, length))
print(select(shrubs, experiment, site))
print(shrubs%>%filter(height>5))
print(shrub_data_w_vols <- mutate(shrubs, "volume" = length*width*height))
