install.packages("dplyr")
library(dplyr)
help(package = "dplyr")
setwd("~/GitHub/r-data-frames-acnicklow")
shrubs <- read.csv("shrub-volume-experiment.csv")
names(shrubs)
str(shrubs)
head(shrubs)
select_all(shrubs)
select(length, site, experiment, everything())
